# Generated by Django 5.0.3 on 2024-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordetails',
            name='visitor_mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
